[package]
name = "dioxus-riverpod"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
dioxus-lib = { version = "0.6", default-features = false, features = [
    "macro",
    "hooks",
    "signals",
] }
tokio = { version = "^1", features = ["sync", "time", "rt"] }
dioxus-riverpod-macros = { path = "./dioxus-riverpod-macros" }
tracing = "0.1"

[dev-dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
tokio = { version = "^1", features = ["time"] }
chrono = { version = "0.4", features = ["std"] }
env_logger = "0.11"
tracing-subscriber = "0.3"

[[example]]
name = "comprehensive_cache_test"
path = "examples/comprehensive_cache_test.rs"

[[example]]
name = "auto_dispose_demo"
path = "examples/auto_dispose_demo.rs"
