[package]
name = "dioxus-riverpod"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
dioxus-lib = { version = "0.6", default-features = false, features = [
    "macro",
    "hooks",
    "signals",
] }
tokio = { version = "^1", features = ["sync", "time", "rt"] }
dioxus-riverpod-macros = { path = "./dioxus-riverpod-macros" }

[dev-dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
tokio = { version = "^1", features = ["time"] }

[[example]]
name = "comprehensive_cache_test"
path = "examples/comprehensive_cache_test.rs"
